### ISSUE TITLE
make not found

### ISSUE THREAD

**Issue by dgustavus** [tionebrr/docker-micropython-tools-esp32#1]
Hi, Just started to play with this as I have found it hard to get the latest version to build with esp-idf. I have followed the README, but when I enter the docker shell with the micropython source, and try to runs a make mpy-cross, I get the response: bash: make: command not found. Sure enough looking around I find cmake, but no make.

Thanks, Duane

**Comment by tionebrr** [comment]
Hi, alright that's weird... I'll try to reproduce the bug.
Can I have more info about your system ?

**Comment by dgustavus** [comment]
Hi,

I am running kubuntu 20.04 on an X64-86 system. I had been working on
building micropython, but was irritated by the fact that the esp-idf 3.3 I
installed was not the same hash, and I did not want to make a
special installation just to build micropython. I saw your note on the
forum, and thought this might be a great way to build micropython because I
do not do it often, and do not want to have to deal with staying at a
particular level.

I think I will try again this weekend, and will copy the steps as I do them
so I can try to help. I am not very experienced with docker, so the problem
may be there.

Cheers, Duane

**Comment by tionebrr** [comment]
Hey Duane, I just pulled a fresh image and I have the same issue.
Will be fixed tonight.

**Comment by dgustavus** [comment]
Thanks a bunch! I will try it again tomorrow.

**Comment by tionebrr** [comment]
Alright. I found other problems while working on the missing packages.
You can build mpy-cross by issuing `CROSS_COMPILE='' make` in the container.
This is not 100% fixed yet. Another 30 minutes for me to test it and it should be good.

**Comment by tionebrr** [comment]
Okay, the new image is up.

**Comment by dgustavus** [comment]
Hi,

I pulled the new version and everything compiles fine! Thanks a bunch.

My goal is to compile the 1.12 version with lvgl on an m5stack which I
would like to use as a monitor for mqtt activity. I hope to get an ESP-MDF
mesh working and need a graphic monitor to verify the activity. It will be
a big help to not have to mess around with the micropython-specific IDF
while also trying to use the latest IDF for the mesh.

Thanks again for the nice tool!
Duane

**Comment by tionebrr** [comment]
You're welcome !
I think the ESP-IDF version on this container (v4.01) is not very far behind the IDF master, but is still labeled as experimental by the Micropython folks... I haven't had a problem yet, but deploy carefully when working on sensitive stuff. 
Also, I may spend a day making an IDFv3 (stable) version of this docker image if some people ask for it ;)
